### ISSUE TITLE
Unable to program

### ISSUE THREAD

**Issue by patzik** [MattisLind/82S100replacement#2]
I had  some pcb's made and tried to build the 82s100 replacement.
I build the lpt cable to program the cpld but I keep getting an error.
"hardware and software settings mismatch"
Any suggestions?
I use a PCIe card with a parallel port, it's lpt1 and the adress is CEFC-CEFF (I/O Range)
I use windows 8, and also tried it  on a virtual machine running xp. Same problem...

**Comment by MattisLind** [comment]
I haven’t tried to use the LPT dongle myself. I always used the USB JTAG dongle. This was controbuted by Github user @jamarju  , you have to ask him.

**Comment by jamarju** [comment]
Double check the schematic taking into account that some pins in the DB25 port loop back: D7-PE, ERROR-GND and D5-ACK. Also make sure you are using version 6.7 of ATMISP, I think that's the only one that supports LPT1 programmers. Also I would try using the standard 378 port just to rule that out.

**Comment by jamarju** [comment]
Oh, and no virtual machines. I think the timings are critical here.

**Comment by patzik** [comment]
It's not really a dongle, but internal PCIe card.
I figured I had and old pc somewhere in storage and I dug it up, it had an onboard parallel port so I installed xp and the Atmel ISP. This port has address 0378 which is the standard IO address.
Works like a charm now, so the cable is fine. I would like to get it to work on my regular pc, but I think the IO address is the cause of the problem, strange because you can actually select the address in the programmer software instead of lpt1

**Comment by jamarju** [comment]
It may be because of I/O to that port going through additional circuitry and/or driver virtualization, who knows. Anyway I'm glad it worked, enjoy @MattisLind 's PLA, I made one for my breadbin C64 and it works great :)

**Comment by pazuzu72** [comment]
Hi, can this project also be used for the C16 / Plus-4, obviously replacing the suitable .PLD? :-)

**Comment by MattisLind** [comment]
I don't know much about what kind of PLA was used in thus computers. As long as it is a 82S100/82S101 it should be possible I think. According to this page it is a 82S100. http://www.zimmers.net/anonftp/pub/cbm/firmware/computers/plus4/pla.c  You have convert the equations to CUPL however.

**Comment by MattisLind** [comment]
I close this issue since there has been long time and the fact it is most likely related to the hardware used.
