### ISSUE TITLE
Equation for Commodore 16

### ISSUE THREAD

**Issue by pazuzu72** [MattisLind/82S100replacement#3]
Hi, your project is **amazing**.  I have made **PLA**s for myself and my friends. 

Since the **PLA** is the same only changes as programmed, I would like to make a version for the **Commodore 16** / **Plus4.**
I don't know where to start from. I tried to understand something but it was in vain. 
Would it be too much for you to convert the equations of the commodore 16? Thanks in advance for what you want to do.

**Comment by MattisLind** [comment]
I need the equations in a proper format so I can translate them into WinCUPL. I googled and apparently there is a guy that has created an ABLE file with the equations. It would be pretty straight forward use that: http://www.jammarcade.net/recreating-the-commodore-16-pla/

Maybe you could check with him if you could get it? I found a JED file but it is targeted for the 82S100 and cannot be used directly. Need the equations.

There is actually a guide on how to convert from ABLE to CUPL: http://ww1.microchip.com/downloads/en/AppNotes/doc3303.pdf

**Comment by pazuzu72** [comment]
In fact I had already found everything you mentioned. 
I will try to ask him if he kindly passes me the equations in ABEL format. Fingers crossed :-)

**Comment by pazuzu72** [comment]
I tried to contact him (Porchy of jammarcade) but on the contact page there is written this: 

_"Everything we have for download is available on the site, everything else is either private or is no longer available here. Any requests for the above will be ignored."_

I looked everywhere but nothing in the ABLE format and I can not convert the equations from the C, I hope sooner or later to succeed.

**Comment by MattisLind** [comment]
Sorry. Cannot help give you any regarding this.
