### ISSUE TITLE
Converting .PLD file to Jedec .JED

### ISSUE THREAD

**Issue by ranger81** [MattisLind/82S100replacement#4]
Hi @MattisLind and @jamarju
I'm trying to program my ATF1502ASL with the PLA code in Atmel ISP with the LPT1 programmer. So far everything seems to be ok, cable works, chip recognized.
However, I cannot use the provided .PLD file in the Atmel ISP software. It keeps telling me to use a .JED Jedec File format.

Could you please tell me how to convert the .PLD to .JDE? A simple rename was not working.

Thanks

**Comment by ranger81** [comment]
Just found this tutorial. The key is, to use the WinCUPL software.
https://ecee.colorado.edu/~mcclurel/ATF16V8C_programming_guide.pdf

**Comment by bandaidboi** [comment]
> Just found this tutorial. The key is, to use the WinCUPL software.
> https://ecee.colorado.edu/~mcclurel/ATF16V8C_programming_guide.pdf

@ranger81 I hate to open this issue back up, but I have been experiencing a problem with go to compile the JEDEC file from the PLD. 

Following the tutorial, WinCupl either crashes or does not output the .JED for me. 
Is there something I am doing wrong or might need to change before I try to compile?

**Comment by ranger81** [comment]
@bandaidboi As far as I remember, I didn't do anything special, just followed the programming guide I have linked.
However, if you need the converted .JED file, message me with your email address and I'll send it to you.

**Comment by bandaidboi** [comment]
@ranger81 Yes!! Please and thanks. I have been trying to get it to work for a few hours and its been a headache. I would greatly appreciate it.

**Comment by ranger81** [comment]
@bandaidboi I have created a fork to which I have uploaded the .JED file. You can find the file here: https://github.com/ranger81/82S100replacement

**Comment by bandaidboi** [comment]
@ranger81 Thanks again! Much appreciated!
